map_type: costmap

obstacle_range: 6.0
raytrace_range: 8.5

transform_tolerance: 10.0

footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]

robot_radius: 0.001 #0.225 
inflation_radius: 0.15
cost_scaling_factor: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}
