map_type: costmap

obstacle_range: 3.0 #1.5
raytrace_range: 3.5 #2.0

transform_tolerance: 0.5 #0.2 

robot_radius: 0.225 
inflation_radius: 0.2 #1.0 #0.5 
cost_scaling_factor: 3.0 #5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}
